# Generated by Django 5.0.3 on 2024-05-07 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='data',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='backup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='backup',
            name='description',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backup',
            name='size_in_mb',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
